### ISSUE TITLE
Upload Box not working

### ISSUE THREAD

**Issue by Devthethird** [Sujimichi/KerbalX#10]
Hi, I'm sorry but I think I broke something in the upload box. I was downloading my new craft when I stupidly closed it, now I cant upload another craft or cancel the half complete previous file. Sorry about this, don't wanna put more on your plate atm. My name on your splendid site is the same as on here.

**Comment by Sujimichi** [comment]
You should have had an option to continue the current upload or cancel it, did that not work?  I shall look into that.  (this has happened to another user this week so there is something awry)

In the meanwhile I have cancelled that upload for you so you should be able to upload again.  
Cheers!

**Comment by Devthethird** [comment]
Sweet thank you, I clicked the cancel/continue download option but I got an error screen (555?). Enjoy your day. :)

**Comment by Sujimichi** [comment]
There was a bug, added in frantic haste while trying to fix the current imgur image problem.  Thanks for reporting this. The fix will be in the next deploy (later today probably, depending on site traffic).
