### ISSUE TITLE
Part Mapper issues

### ISSUE THREAD

**Issue by Shuudoushi** [Sujimichi/KerbalX#11]
Ever since the first time i ran part mapper, all attempts to run it after just fills the log with 301 errors. Like such : http://puu.sh/n9owS/ce54fcb77f.png

Is this something I broke, or is it something that the kerbalstuff shutdown broke?

**Comment by Sujimichi** [comment]
Thanks for pointing that out! No you didn't break anything (it was me, *hangs head)! 
Should be fixed now!

The site was recently changed to use SSL so all http urls are being redirected to https, and the partmapper isn't setup to send ssl requests.  So I've re-enabled http access for the url the partmapper connects to.  
Let me know if you still get errors, if it works then just close this issue.
Cheers!

**Comment by Shuudoushi** [comment]
Works perfectly! http://puu.sh/n9uKc/f084db2fe4.png

Cheers!
