### ISSUE TITLE
Clicking on "KerbalX - Bug Tracker" gives you a 404

### ISSUE THREAD

**Issue by embix** [Sujimichi/KerbalX#14]
Steps to reproduce:

1. go to https://kerbalx.com/dev_blog
2. click on KerbalX - Bug Tracker

The link should be https://github.com/Sujimichi/KerbalX/issues instead of https://kerbalx.com/(https://github.com/Sujimichi/KerbalX/issues

**Comment by Sujimichi** [comment]
Thanks! That's been fixed now.
