### ISSUE TITLE
Inserting a picture from Google Photos causes Error 500

### ISSUE THREAD

**Issue by SYZYGY-DEV333** [Sujimichi/KerbalX#17]
My screenshot for the VTOL Fighter I made will not correctly upload. The image is verified, but a few seconds after inserting it, I am redirected to an Error 500 page. This is reproducible.

Link to craft: [VTOL FIGHTER](https://kerbalx.com/crafts/18313/)
Link to picture: [Google Photos Image](https://lh3.googleusercontent.com/i9OuHhRGedjJdG_gcX0EWWVG-u6IyDUZiKkY8mliB9B2J6i27nUMLEKBX-fxQNgHcTj5KRc2ks6w9jqatZwchSIjBvUlpaZqKON4r6JEi-HlW5BDb9iPXQxo00Hi1OhLrHbFVMKh2AKqcej2tKS3k4LJUv6IxjzCm2RDcE0mwTFjGCMxoh6FrfUy1KlGsLaYLHPXijAGUZoo54dLE6qbEWgNPdmAQklpVKBwM_Eh9YdzeMO7dWa4dibduwR4MoskeyYIp74IeeNQQ29R52u6gyTocGwMGhFPTavc-bHvNbjUeqmdEruhXi6VenC6tVP4IPNg1KBQpjCUNZv95v20CdfvanbsKSEWgfI50vbr0QczoH87uYtdgrLHDdMJzmNBm96Yi7rjoHJstkpfAPOspykrMUhwc-8d5rHGYwUXPha-8IHF2eU2JDxUyQZRpPlVG2m3F4GDB9yhWBVCqV6JTueZ0VglAILwShuhPBvQzvvMPtbfXQ_1S0oixEdOIsT9tXM5f60aGQQxLbjZ0eZToo8q8qDPSMvxqYS_7RrOY-ahAqT_REFZDHs9pVshpoBuH37hCI_uo0fuQNV8o0y4rBb8DaNplOFdmzaPRIgecc-MwONd=w1686-h900-no)

**Comment by Sujimichi** [comment]
The problem is the url length when trying to create a thumbnail from it.  If you use google's url shortener to get a shorter url and then use that it should work.  I just tested it with your image so here's the short url for that image - https://goo.gl/ivPk24
If you use that it should work.

**Comment by SYZYGY-DEV333** [comment]
Fantastic, will do.
