### ISSUE TITLE
Creating a new Hangar causes an Error 500

### ISSUE THREAD

**Issue by Fulgora** [Sujimichi/KerbalX#21]
Tried to create a new public non-open hangar.
Didn't try anything funny in naming it - just plain ASCII (with and without a space)

**Comment by Sujimichi** [comment]
I think you just happened to try this as the awkward moment during a site update (which added a slight change to hangars).  
Try again now, it should be working.

**Comment by Fulgora** [comment]
I got a popup with an update and tried to make a new hanger a few minutes later - thought the update might have caused the bug.

But it works now :)

**Comment by Sujimichi** [comment]
awesome. yeah I think the update popup was a little premature this time, the site hadn't quite finished  restarting everything when it was sent.
