### ISSUE TITLE
[Bug] Email verification warning while not logged in

### ISSUE THREAD

**Issue by TangentFoxy** [Sujimichi/KerbalX#41]
![image](https://user-images.githubusercontent.com/15093567/83834225-9e5c8e00-a6a2-11ea-8347-d9a5097ae495.png)

Also, I have verified my email, so double wtf.

**Comment by Sujimichi** [comment]
Some folk are having trouble with email verification and some of them can't log in, so needed to put link to help in a place everyone can see. If you're verified and you log in you won't see the banner, and I'll remove it in a week or so.
